"use client";
import { useEffect, useState } from "react";
const init = { name:"",email:"",password:"",role:"user" };
export default function Home() {
 const [user,setUser] = useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("visao"),[users,setUsers]=useState([]),[form,setForm]=useState(init),[creds,setCreds]=useState({email:"",password:""}),[passwords,setPasswords]=useState({oldPassword:"",newPassword:""}),[embed,setEmbed]=useState("");
 const request=async(path,body)=>{const res=await fetch(path,{method:body?"POST":"GET",headers:{"Content-Type":"application/json"},cache:"no-store",body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok)throw new Error(data.error||"Erro na solicitação.");return data;};
 const notify=e=>setError(e?.message||"Ocorreu um erro.");
 useEffect(()=>{request("/api/auth").then(d=>{setUser(d.user);setEmbed(d.embedUrl||"")}).catch(notify).finally(()=>setLoading(false));},[]);
 const execute=async(fn)=>{setBusy(true);setError("");try{await fn()}catch(e){notify(e)}finally{setBusy(false)}};
 const refresh=async()=>{const d=await request("/api/auth");setUser(d.user);setEmbed(d.embedUrl||"");};
 const signIn=e=>{e.preventDefault();execute(async()=>{const d=await request("/api/auth",{action:"login",...creds});setUser(d.user);setCreds({email:"",password:""});await refresh()})};
 const signOut=()=>execute(async()=>{await request("/api/auth",{action:"logout"});setUser(null);setUsers([]);setTab("visao")});
 const change=e=>{e.preventDefault();execute(async()=>{await request("/api/auth",{action:"change-password",...passwords});setPasswords({oldPassword:"",newPassword:""});await refresh()})};
 const loadUsers=()=>execute(async()=>{const d=await request("/api/users");setUsers(d.users);setTab("usuarios")});
 const addUser=e=>{e.preventDefault();execute(async()=>{const d=await request("/api/users",{action:"create",...form});setUsers(d.users);setForm(init)})};
 const toggle=u=>execute(async()=>{const d=await request("/api/users",{action:"toggle",id:u.id});setUsers(d.users)});
 const reset=u=>{const value=window.prompt("Senha provisória (mínimo de 12 caracteres) para "+u.name+":");if(value===null)return;execute(async()=>{const d=await request("/api/users",{action:"reset",id:u.id,password:value});setUsers(d.users);window.alert("Senha redefinida. O usuário deverá trocá-la no próximo acesso.")})};
 return <div className="app">
 {(!user||user.changePassword)?<main className="login-shell"><section className="brand-panel"><div className="brand-logo"><span className="logo-bars">▥</span><span>LABORATÓRIO<br/><strong>BOM PASTOR</strong></span></div><div className="brand-message"><span className="eyebrow">PLATAFORMA DE INTELIGÊNCIA</span><h1>Decisões melhores começam com informação.</h1><p>Seus indicadores, relatórios e análises gerenciais em um só lugar.</p></div><small>© 2026 Laboratório Bom Pastor</small></section><section className="login-panel"><div className="login-card">{loading?<p>Carregando...</p>:user?.changePassword?<><div className="circle-icon">✦</div><h2>Defina sua nova senha</h2><p className="muted">Por segurança, troque sua senha provisória antes de continuar.</p><form onSubmit={change}><label>Senha atual<input type="password" required autoComplete="current-password" value={passwords.oldPassword} onChange={e=>setPasswords({...passwords,oldPassword:e.target.value})}/></label><label>Nova senha<input type="password" required minLength={12} autoComplete="new-password" value={passwords.newPassword} onChange={e=>setPasswords({...passwords,newPassword:e.target.value})}/></label><p className="hint">Use pelo menos 12 caracteres.</p><button disabled={busy}>Salvar nova senha</button></form><button className="text-button" onClick={signOut}>Sair da conta</button></>:<><div className="circle-icon">▥</div><span className="eyebrow dark">ACESSO RESTRITO</span><h2>Bem-vindo ao BI</h2><p className="muted">Entre com suas credenciais para acessar o portal.</p><form onSubmit={signIn}><label>E-mail corporativo<input type="email" required autoComplete="username" placeholder="seuemail@empresa.com" value={creds.email} onChange={e=>setCreds({...creds,email:e.target.value})}/></label><label>Senha<input type="password" required autoComplete="current-password" placeholder="Sua senha" value={creds.password} onChange={e=>setCreds({...creds,password:e.target.value})}/></label><button disabled={busy}>Entrar na plataforma <span>→</span></button></form><p className="hint center">Acesso exclusivo para usuários autorizados.</p></>}{error&&<p className="alert" role="alert">{error}</p>}</div></section></main>:
 <div className="workspace"><aside className="sidebar"><div className="side-brand"><span className="brand-mark">▥</span><div>LABORATÓRIO<strong>BOM PASTOR</strong><small>Business Intelligence</small></div></div><p className="nav-label">MENU PRINCIPAL</p><button className={"nav-item "+(tab==="visao"?"active":"")} onClick={()=>{setTab("visao");setError("")}}>▦ <span>Visão geral</span></button><button className={"nav-item "+(tab==="relatorios"?"active":"")} onClick={()=>{setTab("relatorios");setError("")}}>▤ <span>Relatórios BI</span></button>{user.role==="admin"&&<><p className="nav-label">ADMINISTRAÇÃO</p><button className={"nav-item "+(tab==="usuarios"?"active":"")} onClick={loadUsers}>♙ <span>Gerenciar usuários</span></button></>}<div className="sidebar-bottom"><span className="status-dot"/> Sistema gerencial <span className="online">Online</span></div></aside><section className="main-area"><header className="topbar"><span>Portal de Inteligência Gerencial</span><div className="profile"><span className="avatar">{user.name.charAt(0).toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.role==="admin"?"Administrador":"Colaborador"}</small></div><button className="outline small" onClick={signOut}>Sair</button></div></header><div className="content"><div className="section-heading"><div><span className="eyebrow dark">BOM PASTOR • INTELIGÊNCIA</span><h1>{tab==="usuarios"?"Gestão de usuários":tab==="relatorios"?"Relatórios gerenciais":"Visão geral"}</h1><p className="muted">{tab==="usuarios"?"Controle quem pode acessar o ambiente de BI.":tab==="relatorios"?"Acompanhe os seus painéis de indicadores.":"Bem-vindo ao seu ambiente de decisões."}</p></div><div className="pill">● Ambiente interno</div></div>
 {tab==="visao"?<><div className="welcome-banner"><div><span className="eyebrow">INTELIGÊNCIA DE NEGÓCIOS</span><h2>Dados que orientam resultados.</h2><p>Acesse os dashboards e acompanhe o desempenho do laboratório de forma centralizada.</p><button className="white-button" onClick={()=>setTab("relatorios")}>Explorar relatórios →</button></div><div className="banner-art">▥</div></div><div className="tiles"><div className="tile"><div className="tile-icon">▤</div><h3>Painéis analíticos</h3><p>Visualize os relatórios corporativos do Power BI.</p><button className="link" onClick={()=>setTab("relatorios")}>Abrir relatórios →</button></div>{user.role==="admin"&&<div className="tile"><div className="tile-icon">♙</div><h3>Acessos e permissões</h3><p>Crie usuários, redefina senhas e controle o acesso.</p><button className="link" onClick={loadUsers}>Gerenciar usuários →</button></div>}<div className="tile"><div className="tile-icon">◷</div><h3>Acesso simplificado</h3><p>Consulte seus indicadores onde estiver, com acesso autenticado.</p></div></div></>:null}
 {tab==="relatorios"&&<div className="report-box"><div className="report-head"><div><h3>Dashboard executivo</h3><p className="muted">Painel incorporado do Power BI</p></div><span className="pill">Power BI</span></div>{embed?<iframe title="Análises comerciais" src={embed} allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>:<div className="empty"><div className="empty-icon">▤</div><h3>Relatório ainda não configurado</h3><p>O administrador deve inserir o link de incorporação na variável POWERBI_EMBED_URL da Vercel.</p></div>}</div>}
 {tab==="usuarios"&&user.role==="admin"&&<><div className="admin-grid"><section className="panel"><h3>Novo usuário</h3><p className="muted">Cadastre um acesso com senha provisória.</p><form onSubmit={addUser}><label>Nome completo<input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome do colaborador"/></label><label>E-mail<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="email@empresa.com"/></label><label>Senha provisória<input type="password" required minLength={12} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Pelo menos 12 caracteres"/></label><label>Perfil<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="user">Usuário</option><option value="admin">Administrador</option></select></label><button disabled={busy}>+ Criar usuário</button></form></section><section className="panel users-panel"><div className="users-head"><h3>Usuários cadastrados</h3><span className="count">{users.length}</span></div><div className="user-list">{users.map(u=><div className="user-row" key={u.id}><span className="avatar muted-avatar">{u.name.charAt(0).toUpperCase()}</span><div className="user-info"><strong>{u.name}</strong><small>{u.email}</small><div className="tags"><span>{u.role==="admin"?"Administrador":"Usuário"}</span><span className={u.active?"ok":"inactive"}>{u.active?"Ativo":"Inativo"}</span>{u.changePassword&&<span>Troca pendente</span>}</div></div><div className="user-actions"><button className="outline small" onClick={()=>reset(u)}>Redefinir senha</button>{u.id!=="owner"&&u.id!==user.id&&<button className="outline small" onClick={()=>toggle(u)}>{u.active?"Desativar":"Ativar"}</button>}</div></div>)}</div></section></div></>}
 {error&&<p className="alert" role="alert">{error}</p>}</div></section></div>}
 </div>;
}
